const reslist=[
     {
    id: 1,
    title: "Sony WH-1000XM3...",
    image: "https://storage...",
    price: 773,
    description: "Industry leading Active Noise...",
    brand: "sony",
    model: "WH-1000XM3",
    color: "silver",
    category: "audio",
    discount: 11,
    avgRating:4.4
  },
  {
    id: 2,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:4.1
  },
  {
    id: 3,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.9
  },
    
    {
    id: 4,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.4
  },
      {
    id: 5,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.9
  },
    {
    id: 6,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.8,
  },
     {
    id: 7,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:4.3
  },
     {
    id: 8,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.7
  },
     {
    id: 9,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:4.0
  },
     {
    id: 10,
    title: "Microsoft Xbox...",
    image: "https://storage...",
    price: 57,
    description: "Experience the modernized design of the Xbox...",
    brand: "microsoft",
    model: "Xbox X/S",
    color: "white",
    category: "gaming",
    popular: true,
    discount: 4,
    avgRating:3.6
  },
  
]
export default reslist;
